### ISSUE TITLE
Its not working for me 

### ISSUE THREAD

**Issue by krishna-xebia** [claranet/ssha#71]
Traceback (most recent call last):
  File "/usr/bin/ssha", line 9, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/ssha/cli.py", line 47, in main
    ssm.send_command(instance, bastion)
  File "/usr/lib/python2.7/site-packages/ssha/ssm.py", line 84, in send_command
    instance_ids=instance_ids,
  File "/usr/lib/python2.7/site-packages/ssha/ssm.py", line 25, in _send_command
    Parameters=parameters,
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameters: An error occurred (InvalidParameters) when calling the SendCommand operation:

**Comment by raymondbutcher** [comment]
Hi @krishna-xebia, can I see your `.ssha` file?

**Comment by raymondbutcher** [comment]
I just ran into this error. It happened because this part of the `.ssha` file specified parameters that weren't the same as those in the SSM document.

```
ssm {
  session_manager = true

  document {
    name = "add-ssh-key"
  }

  parameters {
    username = ["${ssh.username}"]
    key      = ["$(cat '${ssh.identityfile_public}')"]
  }
}
```

E.g. if the SSM document doesn't accept `username` and `key` parameters then you get an `InvalidParameters` error.
